name: betterscan

on: push

jobs:
    betterscan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: Betterscan Scan
              uses: topcodersonline/betterscan@v3