name: betterscan

on: push

jobs:
    betterscan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - run: |
                echo "Checking out repository"
                ls -la
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Betterscan Scan
              run: |
                echo "Running Betterscan"
                curl https://dl.betterscan.io/cli-html.sh > cli-html.sh
                chmod +x cli-html.sh
                ls -la
                cat cli-html.sh