name: betterscan

on: push

jobs:
    betterscan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: Betterscan Scan
              run: |
                echo "Running Betterscan"
                sh <(curl https://dl.betterscan.io/cli-html.sh)
                ls -la