name: betterscan

on: push

jobs:
    betterscan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: Betterscan Scan
              uses: topcodersonline/betterscan@v3
            - name: Upload the SARIF file
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: report.sarif